// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace aibotPro.Models
{
    public partial class AIBookPortraitImage
    {
        [Key]
        public int Id { get; set; }
        [StringLength(50)]
        public string BookCode { get; set; }
        public string PortraitImage { get; set; }
        public string Overview { get; set; }
        public int? LastChapterId { get; set; }
        public bool? IsDel { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateTime { get; set; }
    }
}