// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace aibotPro.Models
{
    public partial class AIBook
    {
        [Key]
        public int Id { get; set; }
        [StringLength(50)]
        public string BookCode { get; set; }
        [StringLength(50)]
        public string Account { get; set; }
        [StringLength(50)]
        public string BookName { get; set; }
        [StringLength(1000)]
        public string BookThumbnail { get; set; }
        [StringLength(1000)]
        public string BookImg { get; set; }
        [StringLength(50)]
        public string BookType { get; set; }
        [StringLength(1000)]
        public string BookRemark { get; set; }
        [StringLength(500)]
        public string BookTag { get; set; }
        public int? BookWordCount { get; set; }
        public bool? IsPublic { get; set; }
        public bool? IsDel { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateTime { get; set; }
    }
}