// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace aibotPro.Models
{
    [Table("AIdraw")]
    public partial class AIdraw
    {
        [Key]
        public int Id { get; set; }
        [StringLength(50)]
        public string ModelName { get; set; }
        [StringLength(100)]
        public string BaseUrl { get; set; }
        [StringLength(100)]
        public string ApiKey { get; set; }
    }
}