// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace aibotPro.Models
{
    public partial class AIdrawRe
    {
        [Key]
        public int Id { get; set; }
        [StringLength(100)]
        public string Account { get; set; }
        [StringLength(50)]
        public string AImodel { get; set; }
        public string ImgSavePath { get; set; }
        public string Prompt { get; set; }
        public string ReferenceImgPath { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateTime { get; set; }
        public int? IsDel { get; set; }
    }
}