// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace aibotPro.Models;

[Table("AIGroupSetting")]
public partial class AIGroupSetting
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    public string GroupCode { get; set; }

    [StringLength(2000)]
    public string SettingJson { get; set; }
}