// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace aibotPro.Models;

[Table("AIGroupChatHistory")]
public partial class AIGroupChatHistory
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    public string ChatCode { get; set; }

    [StringLength(50)]
    public string GroupCode { get; set; }

    [StringLength(50)]
    public string Account { get; set; }

    [StringLength(50)]
    public string Role { get; set; }

    public string ChatContent { get; set; }

    [StringLength(2000)]
    public string Images { get; set; }

    [StringLength(2000)]
    public string Files { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreateTime { get; set; }

    public bool? IsDel { get; set; }
}