// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace aibotPro.Models;

[Table("AIGroup")]
public partial class AIGroup
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    public string GroupCode { get; set; }

    [StringLength(255)]
    public string GroupName { get; set; }

    [StringLength(50)]
    public string OwnerAccount { get; set; }

    [StringLength(500)]
    public string AIModels { get; set; }

    [StringLength(50)]
    public string Password { get; set; }

    public bool? IsPublic { get; set; }

    public bool? IsDel { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreateTime { get; set; }
}