// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace aibotPro.Models
{
    [Table("AssistantModelPrice")]
    public partial class AssistantModelPrice
    {
        [Key]
        public int Id { get; set; }
        [StringLength(50)]
        public string ModelNick { get; set; }
        [StringLength(50)]
        public string ModelName { get; set; }
        [StringLength(200)]
        public string ApiKey { get; set; }
        [StringLength(200)]
        public string BaseUrl { get; set; }
        [Column(TypeName = "money")]
        public decimal? InputPrice { get; set; }
        [Column(TypeName = "money")]
        public decimal? OutputPrice { get; set; }
        [Column(TypeName = "money")]
        public decimal? VipInputPrice { get; set; }
        [Column(TypeName = "money")]
        public decimal? VipOutputPrice { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? Rebate { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? VipRebate { get; set; }
        [Column(TypeName = "money")]
        public decimal? ConstantPrice { get; set; }
        [Column(TypeName = "money")]
        public decimal? VipConstant { get; set; }
    }
}