// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace aibotPro.Models
{
    [Table("Card")]
    public partial class Card
    {
        [Key]
        public int Id { get; set; }
        [StringLength(50)]
        public string CardNo { get; set; }
        [Column(TypeName = "money")]
        public decimal? Mcoin { get; set; }
        [StringLength(50)]
        public string VipType { get; set; }
        public int? VipDay { get; set; }
        [StringLength(50)]
        public string Account { get; set; }
        [StringLength(50)]
        public string UseAccount { get; set; }
        public int? Used { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateTime { get; set; }
    }
}