// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace aibotPro.Models
{
    [Table("ChatCollection")]
    public partial class ChatCollection
    {
        [Key]
        public int Id { get; set; }
        [StringLength(50)]
        public string CollectionName { get; set; }
        [StringLength(50)]
        public string CollectionCode { get; set; }
        [StringLength(50)]
        public string Account { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateTime { get; set; }
        public bool? IsDel { get; set; }
    }
}