// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace aibotPro.Models
{
    [Table("ChatHistory")]
    public partial class ChatHistory
    {
        [Key]
        public int Id { get; set; }
        [StringLength(100)]
        public string ChatId { get; set; }
        [StringLength(100)]
        public string ChatCode { get; set; }
        [StringLength(100)]
        public string ChatGroupId { get; set; }
        public string Chat { get; set; }
        [StringLength(50)]
        public string Role { get; set; }
        [StringLength(50)]
        public string Model { get; set; }
        [StringLength(100)]
        public string Account { get; set; }
        [StringLength(50)]
        public string FirstTime { get; set; }
        [StringLength(50)]
        public string AllTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateTime { get; set; }
        public int? IsDel { get; set; }
    }
}