// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace aibotPro.Models;

[Table("DeepResearchChatHistory")]
public partial class DeepResearchChatHistory
{
    [Key]
    public int Id { get; set; }

    [StringLength(500)]
    public string DeepResearchChatId { get; set; }

    [StringLength(500)]
    public string ChatId { get; set; }

    [StringLength(50)]
    public string ChatGroupId { get; set; }

    [StringLength(50)]
    public string Model { get; set; }

    [StringLength(50)]
    public string Account { get; set; }

    [StringLength(50)]
    public string Role { get; set; }

    public string Reasoning { get; set; }

    public string Chat { get; set; }

    [StringLength(3000)]
    public string ImageList { get; set; }

    [StringLength(3000)]
    public string FileList { get; set; }

    public bool? IsShow { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreateTime { get; set; }
}