// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace aibotPro.Models;

[Table("DeepResearchActiveList")]
public partial class DeepResearchActiveList
{
    [Key]
    public int Id { get; set; }

    [StringLength(500)]
    public string ChatId { get; set; }

    [StringLength(50)]
    public string Account { get; set; }

    [StringLength(50)]
    public string Icon { get; set; }

    [StringLength(500)]
    public string Title { get; set; }

    [StringLength(1000)]
    public string ActiveContent { get; set; }

    [StringLength(50)]
    public string ActiveStatus { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreateTime { get; set; }
}