// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace aibotPro.Models;

[Table("DeepResearchList")]
public partial class DeepResearchList
{
    [Key]
    public int Id { get; set; }

    [StringLength(500)]
    public string ChatId { get; set; }

    [StringLength(50)]
    public string Account { get; set; }

    [StringLength(500)]
    public string DeepTitle { get; set; }

    public string DeepDesc { get; set; }

    public string DeepContent { get; set; }

    [StringLength(50)]
    public string Process { get; set; }

    [StringLength(50)]
    public string UseTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreateTime { get; set; }
}