// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace aibotPro.Models
{
    [Table("ForumUserSetting")]
    public partial class ForumUserSetting
    {
        [Key]
        public int Id { get; set; }
        public int? AccountId { get; set; }
        [StringLength(200)]
        public string Introduction { get; set; }
        [StringLength(100)]
        public string WebSite { get; set; }
        [StringLength(50)]
        public string AccessToken { get; set; }
        [Column(TypeName = "money")]
        public decimal? Points { get; set; }
        public bool? Mute { get; set; }
    }
}