// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace aibotPro.Models
{
    [Table("ForumTopicStatement")]
    public partial class ForumTopicStatement
    {
        [Key]
        public int Id { get; set; }
        public int? AccountId { get; set; }
        [StringLength(50)]
        public string Emoji { get; set; }
        public int? TopicId { get; set; }
        public bool? IsDel { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateTime { get; set; }
    }
}