// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace aibotPro.Models
{
    [Table("ForumTopicAddendum")]
    public partial class ForumTopicAddendum
    {
        [Key]
        public int Id { get; set; }
        public int? AccountId { get; set; }
        public int? TopicId { get; set; }
        public string AddendumContent { get; set; }
        public bool? IsDel { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateTime { get; set; }
    }
}