// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace aibotPro.Models
{
    [Keyless]
    public partial class IPlook_Stats_View
    {
        public int? TotalClicks { get; set; }
        public int? TodayClicks { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Date { get; set; }
        public int? Clicks { get; set; }
    }
}