// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace aibotPro.Models
{
    [Table("IPlook")]
    public partial class IPlook
    {
        [Key]
        public int Id { get; set; }
        [StringLength(50)]
        public string IPv4 { get; set; }
        [StringLength(50)]
        public string Address { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LookTime { get; set; }
    }
}