// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace aibotPro.Models
{
    public partial class Plugin
    {
        [Key]
        public int Id { get; set; }
        [StringLength(50)]
        public string Pcode { get; set; }
        [StringLength(100)]
        public string Account { get; set; }
        [StringLength(100)]
        public string Pavatar { get; set; }
        [StringLength(50)]
        public string Pnickname { get; set; }
        [StringLength(200)]
        public string Pfunctionname { get; set; }
        [StringLength(1000)]
        public string Pfunctioninfo { get; set; }
        [StringLength(50)]
        public string Popensource { get; set; }
        [Column(TypeName = "money")]
        public decimal? Pluginprice { get; set; }
        [StringLength(50)]
        public string Pcodemodel { get; set; }
        [StringLength(200)]
        public string Papiurl { get; set; }
        [StringLength(50)]
        public string Pmethod { get; set; }
        [StringLength(50)]
        public string ParamCode { get; set; }
        [StringLength(50)]
        public string PheadersCode { get; set; }
        [StringLength(50)]
        public string PcookiesCode { get; set; }
        public string Pjscode { get; set; }
        [StringLength(50)]
        public string PrunLocation { get; set; }
        [StringLength(50)]
        public string Pusehtml { get; set; }
        [StringLength(50)]
        public string IsPublic { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateTime { get; set; }
    }
}