// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace aibotPro.Models
{
    [Table("RoleSetting")]
    public partial class RoleSetting
    {
        [Key]
        public int Id { get; set; }
        [StringLength(50)]
        public string RoleCode { get; set; }
        [StringLength(500)]
        public string RoleAvatar { get; set; }
        [StringLength(50)]
        public string RoleName { get; set; }
        [StringLength(1000)]
        public string RoleInfo { get; set; }
        public string RoleSystemPrompt { get; set; }
        [StringLength(50)]
        public string RoleChatCode { get; set; }
        [StringLength(50)]
        public string Account { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateTime { get; set; }
    }
}