// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace aibotPro.Models
{
    [Table("RoleChat")]
    public partial class RoleChat
    {
        [Key]
        public int Id { get; set; }
        [StringLength(50)]
        public string RoleChatCode { get; set; }
        public string UserInput { get; set; }
        public string AssistantOutput { get; set; }
    }
}