// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace aibotPro.Models;

[Table("TokenPackage")]
public partial class TokenPackage
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    public string UseAccount { get; set; }

    public int? TokenTotal { get; set; }

    public int? TokenUsage { get; set; }

    [StringLength(50)]
    public string Code { get; set; }

    [StringLength(1000)]
    public string ModelList { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ExpirationTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreateTime { get; set; }
}