// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace aibotPro.Models
{
    [Table("UsersMessage")]
    public partial class UsersMessage
    {
        [Key]
        public long Id { get; set; }
        [StringLength(50)]
        public string Account { get; set; }
        [StringLength(50)]
        public string MessageCode { get; set; }
        public string MessageContent { get; set; }
        [StringLength(3000)]
        public string MessageAttr { get; set; }
        [StringLength(50)]
        public string MessageAttrType { get; set; }
        public int? MessageStatus { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateTime { get; set; }
    }
}