// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace aibotPro.Models;

[Table("VibeCodingChatHistory")]
public partial class VibeCodingChatHistory
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    public string ChatId { get; set; }

    [StringLength(100)]
    public string ChatCode { get; set; }

    [StringLength(100)]
    public string ChatGroupId { get; set; }

    [StringLength(3000)]
    public string ChatTitle { get; set; }

    public string Chat { get; set; }

    public string Reasoning { get; set; }

    [StringLength(50)]
    public string Role { get; set; }

    [StringLength(3000)]
    public string ImageList { get; set; }

    [StringLength(50)]
    public string Model { get; set; }

    [StringLength(50)]
    public string Account { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreateTime { get; set; }

    [StringLength(50)]
    public string Location { get; set; }

    public int? IsDel { get; set; }
}